on:
#  branches considered
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      # 1  - checkout the code using predefined action of github
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: chmod +x ./.github/workflows/scripts/build-android.sh
      - run: ./.github/workflows/scripts/build-android.sh -t debug -v dev  -b 1.0.0 -n 123
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}





# actions - draft
# push to master, main, develop
# pull request on main master